# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the OpenColorIO Project.

branches:
  only:
    - master
    - /^RB-.*$/

version: '{branch}-{build}'
image: Visual Studio 2015
clone_folder: C:\source\ocio
test: auto
configuration:
    - Release
platform:
    - x64
   
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      OCIO_BUILD_LIB: ON
      OCIO_BUILD_DOCS: ON
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      OCIO_BUILD_LIB: OFF
      OCIO_BUILD_DOCS: OFF

install:
  - cinst: python2
  
build_script:
  - echo Running cmake...
  - mkdir _build
  - cd _build
  - cmake 
    -G "%CMAKE_PLATFORM%"
    -DCMAKE_INSTALL_PREFIX=..\_install
    -DBUILD_SHARED_LIBS=%OCIO_BUILD_LIB%
    -DOCIO_BUILD_TESTS=ON
    -DOCIO_BUILD_GPU_TESTS=OFF
    -DOCIO_BUILD_DOCS=%OCIO_BUILD_DOCS%
    -DOCIO_WARNING_AS_ERROR=ON
    -DCMAKE_BUILD_TYPE=%CONFIGURATION%
    -DPYTHON_LIBRARY=C:\Python27-x64\libs\python27.lib
    -DPYTHON_INCLUDE_DIR=C:\Python27-x64\include
    -DPYTHON_EXECUTABLE=C:\Python27-x64\python.exe
    ..
  - cmake --build . --target install --config %CONFIGURATION%
  - ctest -V

matrix:
    fast_finish: true
